import React, { useState, useEffect } from "react";
import { createPortal } from "react-dom";
import { X } from "lucide-react";
import Input from "../../../../shared/components/ui/Input";
import Textarea from "../../../../shared/components/ui/Textarea";
import { color, tw, zIndex, button, getButtonStyles } from "../../../../shared/utils/utils";
import { useLanguage } from "../../../../contexts/LanguageContext";
import CustomFieldsRenderer from "./CustomFieldsRenderer";
import { DEFAULT_MODAL_WIDTH } from "../../configs/configurationPageConfigs";
import type {
  ConfigurationItem,
  ConfigurationPageConfig,
} from "./ConfigurationManager";

interface ConfigurationModalProps {
  isOpen: boolean;
  onClose: () => void;
  item?: ConfigurationItem;
  onSave: (item: Record<string, any>) => Promise<void>;
  isSaving?: boolean;
  config: ConfigurationPageConfig;
}

export default function ConfigurationModal({
  isOpen,
  onClose,
  item,
  onSave,
  isSaving = false,
  config,
}: ConfigurationModalProps) {
  const { t } = useLanguage();
  const [formData, setFormData] = useState<Record<string, any>>({
    name: "",
    description: "",
  });
  const [error, setError] = useState("");
  const [valueAutoGenerated, setValueAutoGenerated] = useState(true);

  useEffect(() => {
    const initialData: Record<string, any> = {
      name: item?.name || "",
      description: item?.description || "",
    };

    // Initialize metadata fields
    if (config.metadataFields) {
      config.metadataFields.forEach((field) => {
        initialData[field.key] = (item as Record<string, any>)?.[field.key] || "";
      });
    }

    setFormData(initialData);
    setError("");
    // Only auto-generate value if creating a new item (not editing)
    setValueAutoGenerated(!item);
  }, [item, isOpen, config.metadataFields]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Validate name
    if (config.nameRequired && !formData.name.trim()) {
      setError(
        t.genericConfig.isRequired.replace("{field}", config.nameLabel)
      );
      return;
    }

    if (formData.name.length > config.nameMaxLength) {
      setError(
        t.genericConfig.mustBeCharactersOrLess
          .replace("{field}", config.nameLabel)
          .replace("{maxLength}", config.nameMaxLength.toString())
      );
      return;
    }

    // Validate description
    if (config.descriptionRequired && !formData.description.trim()) {
      setError(
        t.genericConfig.isRequired.replace("{field}", config.descriptionLabel)
      );
      return;
    }

    if (
      formData.description &&
      formData.description.length > config.descriptionMaxLength
    ) {
      setError(
        t.genericConfig.mustBeCharactersOrLess
          .replace("{field}", config.descriptionLabel)
          .replace("{maxLength}", config.descriptionMaxLength.toString())
      );
      return;
    }

    // Validate metadata fields
    if (config.metadataFields) {
      for (const field of config.metadataFields) {
        const shouldShow = field.condition ? field.condition(formData) : true;
        if (shouldShow && field.required && !formData[field.key]) {
          setError(
            t.genericConfig.isRequired.replace("{field}", field.label)
          );
          return;
        }
      }
    }

    setError("");

    const itemData: Record<string, any> = {
      name: formData.name.trim(),
      description: formData.description.trim() || undefined,
    };

    // Add metadata fields to itemData
    if (config.metadataFields) {
      for (const field of config.metadataFields) {
        const shouldShow = field.condition ? field.condition(formData) : true;
        if (shouldShow) {
          let fieldValue = formData[field.key];

          // Parse JSON strings for specific fields (event_condition)
          if (field.key === "event_condition" && typeof fieldValue === "string" && fieldValue.trim()) {
            try {
              fieldValue = JSON.parse(fieldValue);
            } catch (e) {
              setError("Event Condition must be valid JSON (e.g., {} or {\"status\": \"approved\"})");
              return;
            }
          }

          itemData[field.key] = fieldValue;
        }
      }
    }

    await onSave(itemData);
  };

  if (!isOpen) return null;

  return createPortal(
    <div
      className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4"
      style={{ zIndex: zIndex.modal }}
    >
      <div
        className={`bg-white ${tw.rounded} shadow-2xl w-full max-h-[90vh] overflow-y-auto`}
        style={{ maxWidth: config.modalWidth || DEFAULT_MODAL_WIDTH }}
      >
        <div className="flex items-center justify-between p-6 border-b border-gray-200">
          <h2 className="text-xl font-bold text-gray-900">
            {item ? config.modalTitle.edit : config.modalTitle.create}
          </h2>
          <button
            onClick={onClose}
            className={`p-2 hover:bg-gray-100 ${tw.rounded} transition-colors`}
          >
            <X className="w-5 h-5 text-gray-500" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6">
          <div className="space-y-4">
            {/* Name and other row 0 fields on same line */}
            <div className="flex gap-4">
              {/* Name Field */}
              <div className="flex-1">
                <Input
                  label={`${config.nameLabel}${config.nameRequired ? " *" : ""}`}
                  type="text"
                  value={formData.name}
                  onChange={(value) => {
                    const newName = String(value);
                    setFormData((prev) => {
                      const updated = { ...prev, name: newName };
                      // Auto-generate value field from name if it's a row 0 field and hasn't been manually edited
                      const valueField = config.metadataFields?.find((f) => f.key === "value" && (f.row ?? 0) === 0);
                      if (valueField && valueAutoGenerated && newName) {
                        updated.value = newName.toLowerCase().replace(/\s+/g, "_");
                      }
                      return updated;
                    });
                  }}
                  placeholder={t.genericConfig.enter.replace(
                    "{field}",
                    config.nameLabel.toLowerCase()
                  )}
                  maxLength={config.nameMaxLength}
                  required={config.nameRequired}
                />
              </div>

              {/* From Address Field (if it exists in metadata with row 0) */}
              {config.metadataFields?.find((f) => f.key === "from_address" && (f.row ?? 0) === 0) && (
                <div className="flex-1">
                  <Input
                    label="From Email Address"
                    type="text"
                    value={formData.from_address || ""}
                    onChange={(value) =>
                      setFormData((prev) => ({
                        ...prev,
                        from_address: String(value),
                      }))
                    }
                    placeholder="Enter email address"
                    required
                  />
                </div>
              )}

              {/* Value Field (if it exists in metadata with row 0) */}
              {config.metadataFields?.find((f) => f.key === "value" && (f.row ?? 0) === 0) && (
                <div className="flex-1">
                  <Input
                    label={`${config.metadataFields.find((f) => f.key === "value")?.label} *`}
                    type="text"
                    value={formData.value || ""}
                    onChange={(value) => {
                      setFormData((prev) => ({
                        ...prev,
                        value: String(value),
                      }));
                      setValueAutoGenerated(false);
                    }}
                    placeholder="Auto-generated from name"
                    required
                  />
                </div>
              )}
            </div>

            {/* Description Field */}
            <div>
              <Textarea
                label={`${config.descriptionLabel}${config.descriptionRequired ? " *" : ""}`}
                value={formData.description}
                onChange={(value) =>
                  setFormData((prev) => ({
                    ...prev,
                    description: value,
                  }))
                }
                placeholder={t.genericConfig.enter.replace(
                  "{field}",
                  config.descriptionLabel.toLowerCase()
                )}
                rows={3}
                maxLength={config.descriptionMaxLength}
                required={config.descriptionRequired}
              />
            </div>

            {/* Metadata Fields (excluding from_address and value that have row: 0) */}
            {config.metadataFields && (
              <CustomFieldsRenderer
                fields={config.metadataFields.filter(
                  (f) => f.key !== "from_address" && !(f.key === "value" && f.row === 0)
                )}
                formData={formData}
                onFieldChange={(key, value) =>
                  setFormData((prev) => ({ ...prev, [key]: value }))
                }
              />
            )}
          </div>

          {/* Error Message */}
          {error && (
            <div
              className={`mt-4 p-3 bg-red-50 border border-red-200 ${tw.rounded}`}
            >
              <p className="text-red-700 text-sm">{error}</p>
            </div>
          )}

          {/* Action Buttons */}
          <div className="flex items-center justify-end gap-3 mt-6">
            <button
              type="button"
              onClick={onClose}
              className="transition-colors disabled:opacity-50 disabled:cursor-not-allowed hover:opacity-80 dark:text-white dark:border-white"
              style={getButtonStyles(button.bordered)}
            >
              {t.genericConfig.cancel}
            </button>
            <button
              type="submit"
              disabled={isSaving}
              className={`px-4 py-2 text-white ${tw.rounded} transition-all disabled:opacity-50 disabled:cursor-not-allowed`}
              style={{ backgroundColor: color.primary.action }}
            >
              {isSaving
                ? item
                  ? "Updating..."
                  : "Creating..."
                : item
                  ? "Update"
                  : "Create"}
            </button>
          </div>
        </form>
      </div>
    </div>,
    document.body
  );
}
