export interface DummyKPI {
  id: string;
  name: string;
  category:
    | "System Event"
    | "Customer Device Info"
    | "Usage Metric"
    | "Revenue Metric"
    | "Customer Profile Info";
  subcategory?: string;  // Optional subcategory for filtering (e.g., "Data Revenue", "Voice Revenue")
  description: string;
  dataType: "number" | "string" | "date" | "boolean";
  exampleValue: string | number | boolean;
  source: string;
}

export const dummyKPIs: DummyKPI[] = [
  // System Events
  {
    id: "se-1",
    name: "App Opened",
    category: "System Event",
    description: "Triggered when the customer opens the app.",
    dataType: "date",
    exampleValue: "2026-01-29",
    source: "App Analytics",
  },
  {
    id: "se-2",
    name: "Purchase Completed",
    category: "System Event",
    description: "Triggered when a purchase is completed.",
    dataType: "date",
    exampleValue: "2026-01-28",
    source: "Transaction System",
  },
  {
    id: "se-3",
    name: "SMS Sent",
    category: "System Event",
    description: "Triggered when an SMS is sent to the customer.",
    dataType: "date",
    exampleValue: "2026-01-27",
    source: "Messaging Gateway",
  },
  {
    id: "se-4",
    name: "Login",
    category: "System Event",
    description: "Triggered when the customer logs in.",
    dataType: "date",
    exampleValue: "2026-01-26",
    source: "App Analytics",
  },
  {
    id: "se-5",
    name: "Password Reset",
    category: "System Event",
    description: "Triggered when the customer resets their password.",
    dataType: "date",
    exampleValue: "2026-01-25",
    source: "App Analytics",
  },
  // Customer Device Info
  {
    id: "cd-1",
    name: "Device Type",
    category: "Customer Device Info",
    subcategory: "device_profile",
    description: "Device type (4G/3G/2G)",
    dataType: "string",
    exampleValue: "4G",
    source: "BIB_ADM.FLYTXT_DX_DAILY_KPI",
  },
  {
    id: "cd-2",
    name: "Phone Brand",
    category: "Customer Device Info",
    subcategory: "device_profile",
    description: "Phone brand/manufacturer",
    dataType: "string",
    exampleValue: "Samsung",
    source: "BIB_ADM.FLYTXT_DX_DAILY_KPI",
  },
  {
    id: "cd-3",
    name: "SIM Type",
    category: "Customer Device Info",
    subcategory: "sim_info",
    description: "SIM Type (4G USIM / 3G SIM / Normal)",
    dataType: "string",
    exampleValue: "4G USIM",
    source: "BIB_ADM.FLYTXT_DX_DAILY_KPI",
  },
  {
    id: "cd-4",
    name: "Smartphone",
    category: "Customer Device Info",
    subcategory: "device_profile",
    description: "Whether device is a smartphone",
    dataType: "string",
    exampleValue: "Yes",
    source: "BIB_ADM.FLYTXT_DX_DAILY_KPI",
  },
  {
    id: "cd-5",
    name: "Device Category",
    category: "Customer Device Info",
    subcategory: "device_profile",
    description: "Device category classification",
    dataType: "string",
    exampleValue: "Premium",
    source: "BIB_ADM.FLYTXT_DX_DAILY_KPI",
  },
  // Usage Metrics
  {
    id: "um-1",
    name: "Data 4G Usage New",
    category: "Usage Metric",
    subcategory: "data_usage",
    description: "Data usage on 4G network in MB",
    dataType: "number",
    exampleValue: 1500,
    source: "OCS_DATA",
  },
  {
    id: "um-2",
    name: "Total OG MOU New",
    category: "Usage Metric",
    subcategory: "voice_usage",
    description: "Total outgoing call minutes of usage",
    dataType: "number",
    exampleValue: 320,
    source: "OCS_REC",
  },
  {
    id: "um-3",
    name: "Total SMS Count",
    category: "Usage Metric",
    subcategory: "sms_usage",
    description: "Total SMS sent count",
    dataType: "number",
    exampleValue: 25,
    source: "OCS_SMS",
  },
  {
    id: "um-4",
    name: "Total DOU",
    category: "Usage Metric",
    subcategory: "dou_metrics",
    description: "Total days of usage metric",
    dataType: "number",
    exampleValue: 18,
    source: "BIB_ADM.FLYTXT_DX_DAILY_KPI",
  },
  {
    id: "um-5",
    name: "Offnet OG MOU New",
    category: "Usage Metric",
    subcategory: "voice_usage",
    description: "Off-net outgoing call minutes of usage",
    dataType: "number",
    exampleValue: 95,
    source: "OCS_REC",
  },
  {
    id: "um-6",
    name: "Total Data Usage New",
    category: "Usage Metric",
    subcategory: "data_usage",
    description: "Total data usage across all networks in MB",
    dataType: "number",
    exampleValue: 2500,
    source: "OCS_DATA",
  },
  {
    id: "um-7",
    name: "Refill Count",
    category: "Usage Metric",
    subcategory: "dou_metrics",
    description: "Total count of recharges/refills",
    dataType: "number",
    exampleValue: 5,
    source: "OCS_VOU",
  },
  // Revenue Metrics
  {
    id: "rm-1",
    name: "Total Data Revenue New",
    category: "Revenue Metric",
    subcategory: "data_revenue",
    description: "Total data revenue (PAYGO + Bundle)",
    dataType: "number",
    exampleValue: 450.75,
    source: "OCS_DATA",
  },
  {
    id: "rm-2",
    name: "Total Voice Revenue",
    category: "Revenue Metric",
    subcategory: "voice_revenue",
    description: "Total voice revenue (PAYGO + Bundle)",
    dataType: "number",
    exampleValue: 350.5,
    source: "OCS_REC",
  },
  {
    id: "rm-3",
    name: "Onnet OG Rev New",
    category: "Revenue Metric",
    subcategory: "voice_revenue",
    description: "On-net outgoing call revenue",
    dataType: "number",
    exampleValue: 200.25,
    source: "OCS_REC",
  },
  {
    id: "rm-4",
    name: "Total Revenue Updated",
    category: "Revenue Metric",
    subcategory: "other_revenue",
    description: "Total revenue across all services",
    dataType: "number",
    exampleValue: 1200.0,
    source: "BIB_ADM.FLYTXT_DX_DAILY_KPI",
  },
  {
    id: "rm-5",
    name: "Refill Amount",
    category: "Revenue Metric",
    subcategory: "other_revenue",
    description: "Total recharge/refill amount",
    dataType: "number",
    exampleValue: 500.0,
    source: "OCS_VOU",
  },
  {
    id: "rm-6",
    name: "Total SMS Revenue New",
    category: "Revenue Metric",
    subcategory: "sms_revenue",
    description: "Total SMS revenue (PAYGO + Bundle)",
    dataType: "number",
    exampleValue: 85.25,
    source: "OCS_SMS",
  },
  {
    id: "rm-7",
    name: "IDD OG Rev New",
    category: "Revenue Metric",
    subcategory: "voice_revenue",
    description: "International direct dial outgoing call revenue",
    dataType: "number",
    exampleValue: 125.5,
    source: "OCS_REC",
  },
  // Customer Profile Info
  {
    id: "cp-1",
    name: "Customer Name",
    category: "Customer Profile Info",
    description: "Full name of the customer.",
    dataType: "string",
    exampleValue: "Jane Doe",
    source: "CRM",
  },
  {
    id: "cp-2",
    name: "Date of Birth",
    category: "Customer Profile Info",
    description: "Customer’s date of birth.",
    dataType: "date",
    exampleValue: "1990-05-15",
    source: "CRM",
  },
  {
    id: "cp-3",
    name: "Gender",
    category: "Customer Profile Info",
    description: "Gender of the customer.",
    dataType: "string",
    exampleValue: "Female",
    source: "CRM",
  },
  {
    id: "cp-4",
    name: "Location",
    category: "Customer Profile Info",
    description: "Customer’s location or city.",
    dataType: "string",
    exampleValue: "Kampala",
    source: "CRM",
  },
  {
    id: "cp-5",
    name: "Registration Date",
    category: "Customer Profile Info",
    description: "Date the customer registered.",
    dataType: "date",
    exampleValue: "2022-03-01",
    source: "CRM",
  },
];
