export type UsageMetricCategory =
  | "data_usage"
  | "voice_usage"
  | "sms_usage"
  | "bundle_usage"
  | "dou_metrics";

export type UsageMetricOperator =
  | "equals"
  | "not_equals"
  | "greater_than"
  | "less_than"
  | "in"
  | "not_in";

export interface UsageMetric {
  id: number;
  name: string;
  description: string;
  field_type: "numeric" | "decimal";
  category: UsageMetricCategory;
  operators: UsageMetricOperator[];
  source_table: string;
  data_source: "Live" | "DB";
  frequency: "Per Min" | "D-1" | "Monthly";
  unit?: string;
  default_value?: string | number;
}

export const USAGE_METRICS: UsageMetric[] = [
  {
    id: 1,
    name: "Data 2G Usage New",
    description: "Data usage on 2G network in MB",
    field_type: "decimal",
    category: "data_usage",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_DATA",
    data_source: "Live",
    frequency: "Per Min",
    unit: "MB",
  },
  {
    id: 2,
    name: "Data 3G Usage New",
    description: "Data usage on 3G network in MB",
    field_type: "decimal",
    category: "data_usage",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_DATA",
    data_source: "Live",
    frequency: "Per Min",
    unit: "MB",
  },
  {
    id: 3,
    name: "Data 4G Usage New",
    description: "Data usage on 4G network in MB",
    field_type: "decimal",
    category: "data_usage",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_DATA",
    data_source: "Live",
    frequency: "Per Min",
    unit: "MB",
  },
  {
    id: 4,
    name: "Total Data Usage New",
    description: "Total data usage across all networks in MB",
    field_type: "decimal",
    category: "data_usage",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_DATA",
    data_source: "Live",
    frequency: "Per Min",
    unit: "MB",
  },
  {
    id: 5,
    name: "Total PAYGO Data Usage New",
    description: "Total data usage on pay-as-you-go plan in MB",
    field_type: "decimal",
    category: "data_usage",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_DATA",
    data_source: "Live",
    frequency: "Per Min",
    unit: "MB",
  },
  {
    id: 6,
    name: "Total Data Bundled Usage New",
    description: "Total data usage on bundle plan in MB",
    field_type: "decimal",
    category: "bundle_usage",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_DATA",
    data_source: "Live",
    frequency: "Per Min",
    unit: "MB",
  },
  {
    id: 7,
    name: "Data DOU",
    description: "Data days of usage metric",
    field_type: "numeric",
    category: "dou_metrics",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_DATA",
    data_source: "Live",
    frequency: "Per Min",
    unit: "Days",
  },
  {
    id: 8,
    name: "Data_DOU_Monthly",
    description: "Monthly data days of usage",
    field_type: "numeric",
    category: "dou_metrics",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "BIB_ADM.FLYTXT_DX_DAILY_KPI",
    data_source: "DB",
    frequency: "D-1",
    unit: "Days",
  },

  {
    id: 9,
    name: "Total OG MOU New",
    description: "Total outgoing call minutes of usage",
    field_type: "decimal",
    category: "voice_usage",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_REC",
    data_source: "Live",
    frequency: "Per Min",
    unit: "Minutes",
  },
  {
    id: 10,
    name: "Total IC MOU",
    description: "Total incoming call minutes of usage",
    field_type: "decimal",
    category: "voice_usage",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "BIB_ADM.FLYTXT_DX_DAILY_KPI",
    data_source: "DB",
    frequency: "D-1",
    unit: "Minutes",
  },
  {
    id: 11,
    name: "Onnet OG Mou New",
    description: "On-net outgoing call minutes of usage",
    field_type: "decimal",
    category: "voice_usage",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_REC",
    data_source: "Live",
    frequency: "Per Min",
    unit: "Minutes",
  },
  {
    id: 12,
    name: "Total OnNet OG MOU",
    description: "Total on-net outgoing call minutes of usage",
    field_type: "decimal",
    category: "voice_usage",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_REC",
    data_source: "Live",
    frequency: "Per Min",
    unit: "Minutes",
  },
  {
    id: 13,
    name: "Offnet OG MOU New",
    description: "Off-net outgoing call minutes of usage",
    field_type: "decimal",
    category: "voice_usage",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_REC",
    data_source: "Live",
    frequency: "Per Min",
    unit: "Minutes",
  },
  {
    id: 14,
    name: "IDD OG MOU New",
    description: "International direct dial outgoing call minutes of usage",
    field_type: "decimal",
    category: "voice_usage",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_REC",
    data_source: "Live",
    frequency: "Per Min",
    unit: "Minutes",
  },
  {
    id: 15,
    name: "Bundle OnNet OG MOU",
    description: "On-net outgoing call minutes on bundle plan",
    field_type: "decimal",
    category: "bundle_usage",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_REC",
    data_source: "Live",
    frequency: "Per Min",
    unit: "Minutes",
  },
  {
    id: 16,
    name: "Payg OnNet OG MOU",
    description: "On-net outgoing call minutes on pay-as-you-go plan",
    field_type: "decimal",
    category: "voice_usage",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_REC",
    data_source: "Live",
    frequency: "Per Min",
    unit: "Minutes",
  },
  {
    id: 17,
    name: "Total Roaming Usage New",
    description: "Total roaming call minutes of usage",
    field_type: "decimal",
    category: "voice_usage",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_REC",
    data_source: "Live",
    frequency: "Per Min",
    unit: "Minutes",
  },

  {
    id: 18,
    name: "Total SMS Count",
    description: "Total SMS sent count",
    field_type: "numeric",
    category: "sms_usage",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_SMS",
    data_source: "Live",
    frequency: "Per Min",
    unit: "Count",
  },

  {
    id: 19,
    name: "Total DOU",
    description: "Total days of usage metric",
    field_type: "numeric",
    category: "dou_metrics",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "BIB_ADM.FLYTXT_DX_DAILY_KPI",
    data_source: "Live",
    frequency: "Per Min",
    unit: "Days",
  },
  {
    id: 20,
    name: "Total_DOU_Monthly",
    description: "Monthly total days of usage",
    field_type: "numeric",
    category: "dou_metrics",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "BIB_ADM.FLYTXT_DX_DAILY_KPI",
    data_source: "DB",
    frequency: "Monthly",
    unit: "Days",
  },
  {
    id: 21,
    name: "Voice_DOU_Monthly",
    description: "Monthly voice days of usage",
    field_type: "numeric",
    category: "dou_metrics",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "BIB_ADM.FLYTXT_DX_DAILY_KPI",
    data_source: "DB",
    frequency: "Monthly",
    unit: "Days",
  },
  {
    id: 22,
    name: "Recharge DOU",
    description: "Days of usage based on recharge activity",
    field_type: "numeric",
    category: "dou_metrics",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_VOU",
    data_source: "Live",
    frequency: "Per Min",
    unit: "Days",
  },
  {
    id: 23,
    name: "Refill Count",
    description: "Total count of recharges/refills",
    field_type: "numeric",
    category: "dou_metrics",
    operators: ["equals", "not_equals", "greater_than", "less_than", "in", "not_in"],
    source_table: "OCS_VOU",
    data_source: "Live",
    frequency: "Per Min",
    unit: "Count",
  },
];

export const USAGE_METRICS_BY_CATEGORY = {
  data_usage: USAGE_METRICS.filter((m) => m.category === "data_usage"),
  voice_usage: USAGE_METRICS.filter((m) => m.category === "voice_usage"),
  sms_usage: USAGE_METRICS.filter((m) => m.category === "sms_usage"),
  bundle_usage: USAGE_METRICS.filter((m) => m.category === "bundle_usage"),
  dou_metrics: USAGE_METRICS.filter((m) => m.category === "dou_metrics"),
};

export const USAGE_METRIC_CATEGORIES = [
  { value: "data_usage", label: "Data Usage" },
  { value: "voice_usage", label: "Voice Usage" },
  { value: "sms_usage", label: "SMS Usage" },
  { value: "bundle_usage", label: "Bundle Usage" },
  { value: "dou_metrics", label: "DOU Metrics" },
] as const;
